name: RotMC
version: 1.0.0
author: FreakzBoy

main: me.kench.rotmc.RotMcPlugin
api-version: 1.16
softdepend: [ PlaceholderAPI, LuckPerms, Guilds, WorldGuard ]

commands:
  glow:
    description: Opens Glow-GUI
    aliases: [ glowgui, glows ]
  gtop:
    description: Used to display guilds-fame related stuff
  ftop:
    description: Used to display class-fame related stuff
    aliases: [ f, fames, fame ]
  stats:
    description: Used to display your stats
    aliases: [ stat, skill, skills ]
  class:
    description: Used to select your class
    aliases: classes
  rotmc:
    description: Best command out of all